# _quarto-standalone.yml
project:
  output-dir: standalone
  resources: "!slides"

format:
  html:
    extends: html
    embed-resources: true
    toc: true
    toc-title: Contents
    toc-expand: 1
    sidebar: false
    page-navigation: false

lightbox: true